//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Synthie.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_SynthieTYPE                 130
#define IDD_PROGRESS_DLG                131
#define IDS_EDIT_MENU                   306
#define IDR_WAVE14                      407
#define IDR_A0SH                        409
#define IDR_A0                          410
#define IDR_A1SH                        411
#define IDR_A1                          412
#define IDR_A2SH                        413
#define IDR_A2                          414
#define IDR_A3SH                        415
#define IDR_A3                          416
#define IDR_A4SH                        417
#define IDR_A4                          418
#define IDR_A5SH                        419
#define IDR_A5                          420
#define IDR_A6SH                        421
#define IDR_A6                          422
#define IDR_A7SH                        423
#define IDR_A7                          424
#define IDR_B0                          425
#define IDR_B1                          426
#define IDR_B2                          427
#define IDR_B3                          428
#define IDR_B4                          429
#define IDR_B5                          430
#define IDR_B6                          431
#define IDR_B7                          432
#define IDR_C1SH                        433
#define IDR_C1                          434
#define IDR_C2SH                        435
#define IDR_C2                          436
#define IDR_C3SH                        437
#define IDR_C3                          438
#define IDR_C4SH                        439
#define IDR_C4                          440
#define IDR_C5SH                        441
#define IDR_C5                          442
#define IDR_C6SH                        443
#define IDR_C6                          444
#define IDR_C7SH                        445
#define IDR_C7                          446
#define IDR_C8                          447
#define IDR_D1SH                        448
#define IDR_D1                          449
#define IDR_D2SH                        450
#define IDR_D2                          451
#define IDR_D3SH                        452
#define IDR_D3                          453
#define IDR_D4SH                        454
#define IDR_D4                          455
#define IDR_D5SH                        456
#define IDR_D5                          457
#define IDR_D6SH                        458
#define IDR_D6                          459
#define IDR_D7SH                        460
#define IDR_D7                          461
#define IDR_E1                          462
#define IDR_E2                          463
#define IDR_E3                          464
#define IDR_E4                          465
#define IDR_E5                          466
#define IDR_E6                          467
#define IDR_E7                          468
#define IDR_F1SH                        469
#define IDR_F1                          470
#define IDR_F2SH                        471
#define IDR_F2                          472
#define IDR_F3SH                        473
#define IDR_F3                          474
#define IDR_F4SH                        475
#define IDR_F4                          476
#define IDR_F5SH                        477
#define IDR_F5                          478
#define IDR_F6SH                        479
#define IDR_F6                          480
#define IDR_F7SH                        481
#define IDR_F7                          482
#define IDR_G1SH                        483
#define IDR_G1                          484
#define IDR_G2SH                        485
#define IDR_G2                          486
#define IDR_G3SH                        487
#define IDR_G3                          488
#define IDR_G4SH                        489
#define IDR_G4                          490
#define IDR_G5SH                        491
#define IDR_G5                          492
#define IDR_G6SH                        493
#define IDR_G6                          494
#define IDR_G7SH                        495
#define IDR_G7                          496
#define IDR_PEDALD                      497
#define IDR_WAVE1                       498
#define IDR_PEDALU                      498
#define IDC_PROGRESS                    1000
#define IDC_STOP                        1001
#define ID_GENERATE_FILEOUTPUT          32771
#define ID_GENERATE_AUDIOOUTPUT         32772
#define ID_GENERATE_1000HZTONE          32773
#define ID_GENERATE_SYNTHESIZER         32774
#define ID_FILE_OPENSCORE               32775
#define ID_GENERATE_SEQUENCER           32776
#define ID_FILE_OPEN32777               32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        499
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
