//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Synthie.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_SynthieTYPE                 130
#define IDD_PROGRESS_DLG                131
#define IDS_EDIT_MENU                   306
#define IDR_PEDALD                      310
#define IDR_PEDALU                      311
#define IDR_A0SH                        312
#define IDR_A0                          313
#define IDR_A1SH                        314
#define IDR_A1                          315
#define IDR_A2SH                        316
#define IDR_A2                          317
#define IDR_A3SH                        318
#define IDR_A3                          319
#define IDR_A4SH                        320
#define IDR_A4                          321
#define IDR_A5SH                        322
#define IDR_A5                          323
#define IDR_A6SH                        324
#define IDR_A6                          325
#define IDR_A7SH                        326
#define IDR_A7                          327
#define IDR_B0                          336
#define IDR_B1                          337
#define IDR_B2                          338
#define IDR_B3                          339
#define IDR_B4                          340
#define IDR_B5                          341
#define IDR_B6                          342
#define IDR_B7                          343
#define IDR_C1SH                        344
#define IDR_C1                          345
#define IDR_C2SH                        346
#define IDR_C2                          347
#define IDR_C3SH                        348
#define IDR_C3                          349
#define IDR_C4SH                        350
#define IDR_C4                          351
#define IDR_C5SH                        352
#define IDR_C5                          353
#define IDR_C6SH                        354
#define IDR_C6                          355
#define IDR_C7SH                        356
#define IDR_C7                          357
#define IDR_C8                          358
#define IDR_D1SH                        359
#define IDR_D1                          360
#define IDR_D2SH                        361
#define IDR_D2                          362
#define IDR_D3SH                        363
#define IDR_D3                          364
#define IDR_D4SH                        365
#define IDR_D4                          366
#define IDR_D5SH                        367
#define IDR_D5                          368
#define IDR_D6SH                        369
#define IDR_D6                          370
#define IDR_D7SH                        371
#define IDR_D7                          372
#define IDR_E1                          373
#define IDR_E2                          374
#define IDR_E3                          375
#define IDR_E4                          376
#define IDR_E5                          377
#define IDR_E6                          378
#define IDR_E7                          379
#define IDR_F1SH                        380
#define IDR_F1                          381
#define IDR_F2SH                        382
#define IDR_F2                          383
#define IDR_F3SH                        384
#define IDR_F3                          385
#define IDR_F4SH                        386
#define IDR_F4                          387
#define IDR_F5SH                        388
#define IDR_F5                          389
#define IDR_F6SH                        390
#define IDR_F6                          391
#define IDR_F7SH                        392
#define IDR_F7                          393
#define IDR_G1SH                        394
#define IDR_G1                          395
#define IDR_G2SH                        396
#define IDR_G2                          397
#define IDR_G3SH                        398
#define IDR_G3                          399
#define IDR_G4SH                        400
#define IDR_G4                          401
#define IDR_G5SH                        402
#define IDR_G5                          403
#define IDR_G6SH                        404
#define IDR_G6                          405
#define IDR_G7SH                        406
#define IDR_WAVE14                      407
#define IDR_G7                          407
#define IDC_PROGRESS                    1000
#define IDC_STOP                        1001
#define ID_GENERATE_FILEOUTPUT          32771
#define ID_GENERATE_AUDIOOUTPUT         32772
#define ID_GENERATE_1000HZTONE          32773
#define ID_GENERATE_SYNTHESIZER         32774
#define ID_FILE_OPENSCORE               32775
#define ID_GENERATE_SEQUENCER           32776
#define ID_FILE_OPEN32777               32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        408
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
